---
title: "Research Project"
output: html_document
date: "2023-11-08"
---
```{r}

library(ggplot2)
library(dplyr)
library(visreg)
library(tidyverse)
library(readr)
library(lubridate)
library(knitr)
```

```{r}
AC_Data_2022 <- read.csv("~/MazerResearchProject/Data/AC_Data_2022.csv")
view(AC_Data_2022)
```

```{r}
names(AC_Data_2022)
#Remember to log Stem Biomass#

min(AC_Data_2022$Stem_Biomass, na.rm = TRUE) #Dont need to add 1 wooooo#
#min = 1.35#

AC_Data_2022 <- AC_Data_2022 %>% mutate (Log_Stem_Biomass = log(Stem_Biomass))
```
```{r}
#Separate transects#

ACTransect1 <- subset(AC_Data_2022, Transect == 1)
ACTransect2 <- subset(AC_Data_2022, Transect == 2)
ACTransect3 <- subset(AC_Data_2022, Transect == 3)
ACTransect4 <- subset(AC_Data_2022, Transect == 4)
ACTransect5 <- subset(AC_Data_2022, Transect == 5)
ACTransect6 <- subset(AC_Data_2022, Transect == 6)
ACTransect7 <- subset(AC_Data_2022, Transect == 7)
ACTransect8 <- subset(AC_Data_2022, Transect == 8)
ACTransect9 <- subset(AC_Data_2022, Transect == 9)

# Creating mean-centering function

center_scale <- function(x) {
  scale(x, scale = FALSE)
}



```

```{r}
#Remove outliers for Transect 1#
PopulationV1 <- ACTransect1$Population 
Field_YearV1 <- ACTransect1$Field_Year
GenerationV1 <- ACTransect1$Generation
BlockV1 <- ACTransect1$Block
TransectV1 <- ACTransect1$Transect
SequenceV1 <- ACTransect1$Sequence
DonorV1 <- ACTransect1$Donor
RecipientV1 <- ACTransect1$Recipient
FFDV1 <- ACTransect1$FFD
LFDV1 <- ACTransect1$LFD


ACTransect1$Population <-NULL
ACTransect1$Field_Year <- NULL
ACTransect1$Generation <- NULL
ACTransect1$Block <- NULL
ACTransect1$Transect <- NULL
ACTransect1$Sequence <- NULL
ACTransect1$Donor <- NULL
ACTransect1$Recipient <- NULL
ACTransect1$FFD <- NULL
ACTransect1$LFD <- NULL

z_scores <- as.data.frame(sapply(ACTransect1, function(ACTransect1) (abs(ACTransect1-mean(ACTransect1, na.rm = TRUE))/sd(ACTransect1, na.rm = TRUE))))

class(z_scores)

View(z_scores) 

for(i in 1:nrow(z_scores)){
  for(j in 1:ncol(z_scores)){
    if(is.na(z_scores[i,j])){
      ACTransect1[i,j] = NA
    }
      else if(z_scores[i,j] > 3){
      ACTransect1[i,j] = NA
      }
    }
  }

ACTransect1 <- ACTransect1 %>% 
  mutate(Population = PopulationV1 , Field_Year = Field_YearV1, Generation = GenerationV1, Block = BlockV1, Transect = TransectV1, Sequence = SequenceV1, Donor = DonorV1, Recipient = RecipientV1, FFD = FFDV1, LFD = LFDV1, .before = Left_Or_Right, )

View(ACTransect1)
```


```{r}
#Calculate mean phenotype of maternal genotype separated by transect to account for environmental effects on each transect#
Recipient1 <- c(ACTransect1$Recipient)
Variable1 <- c("Recipient","Stem_Biomass")
ACTransect1Pop <- rbind(ACTransect1, na.rm = TRUE)
ACTransect1Pop <- ACTransect1Pop[Variable1]
ACTransect1Pop <- na.omit(ACTransect1Pop)

MaternalMean1 <- mean(ACTransect1Pop$Stem_Biomass, na.rm = TRUE)
#Calculate genetic variance of maternal genotype in Transect 1
var(ACTransect1Pop$Stem_Biomass, na.rm = FALSE)
mean(ACTransect1Pop$Stem_Biomass, na.rm = FALSE)
min(ACTransect1Pop$Stem_Biomass, na.rm = FALSE)
max(ACTransect1Pop$Stem_Biomass, na.rm = FALSE)
```


```{r}
Recipients <- c(ACTransect1$Recipient, ACTransect2$Recipient, ACTransect3$Recipient, ACTransect4$Recipient, ACTransect5$Recipient, ACTransect6$Recipient, ACTransect7$Recipient, ACTransect8$Recipient, ACTransect9$Recipient)

Variable <- c("Recipient", "Stem_Biomass")

Maternal <- rbind(ACTransect1,ACTransect2,ACTransect3,ACTransect4,ACTransect5,ACTransect6,ACTransect7,ACTransect8, ACTransect9)
Maternal <- Maternal[Variable]
Maternal <- Maternal[order(Maternal$Recipient, decreasing = TRUE),]
```

```{r}
#Calculate paternal genotype mean
Donor1 <- c(ACTransect1$Donor)
DonorVariable1 <- c("Donor","Stem_Biomass")
ACTransect1PopDonor <- rbind(ACTransect1, na.rm = TRUE)
ACTransect1PopDonor <- ACTransect1PopDonor[DonorVariable1]
ACTransect1PopDonor[is.na(ACTransect1PopDonor)] <- 0

DonorMean <- ACTransect1PopDonor %>%
  group_by(Donor) %>%
  summarize(Stem_Biomass = mean(Stem_Biomass))
#calculate genetic variance of stem biomass in paternal genotypes in Transect 1
var(DonorMean$Stem_Biomass, na.rm=TRUE)
```

#Start on line 697 to begin mean centering stuff#
```{r}
ACTransect1 <- ACTransect1 %>% mutate(Log_Stem_BiomassMC = center_scale(Log_Stem_Biomass))
mean(ACTransect1$Log_Stem_BiomassMC, na.rm = TRUE)
min(ACTransect1$Log_Stem_BiomassMC, na.rm = TRUE)
max(ACTransect1$Log_Stem_BiomassMC, na.rm = TRUE)

Recipient1Log <- c(ACTransect1$Recipient)
Variable1Log <- c("Recipient","Log_Stem_BiomassMC")
ACTransect1PopLog <- rbind(ACTransect1, na.rm = TRUE)
ACTransect1PopLog <- ACTransect1PopLog[Variable1Log]
ACTransect1PopLog <- na.omit(ACTransect1PopLog)

MaternalMean1Log <- mean(ACTransect1Pop$Log_Stem_BiomassMC, na.rm = TRUE)
#Calculate genetic variance of maternal genotype in Transect 1
var(ACTransect1PopLog$Log_Stem_BiomassMC, na.rm = TRUE)

Donor1Log <- c(ACTransect1$Donor)
DonorVariable1Log <- c("Donor","Log_Stem_BiomassMC")
ACTransect1PopDonorLog <- rbind(ACTransect1, na.rm = TRUE)
ACTransect1PopDonorLog <- ACTransect1PopDonorLog[DonorVariable1Log]

DonorMeanLog <- ACTransect1PopDonorLog %>%
  group_by(Donor) %>%
  summarize(Log_Stem_BiomassMC = mean(Log_Stem_BiomassMC))
#calculate genetic variance of stem biomass in paternal genotypes in Transect 1
var(DonorMeanLog$Log_Stem_BiomassMC, na.rm=TRUE)
```
#Look into mixed models. a <- lmer(StemBiomass ~ matid + patid) . thats the code you should be using to look at regression. Then to get variance of maternal id and paternal id in relation to stem biomass youll use the code : varcomp(a)#

```{r}
list.files()
file.exists("DataFromOtherCode.Rmd")
source("~/MazerResearchProject/DataFromOtherCode.Rmd")
file.exists("DataFromOtherCode.Rmd")
knitr::knit("~/MazerResearchProject/DataFromOtherCode.Rmd", output = NULL)

var(AC_Avg_MC_Population$AMC_Log_Stem_Biomass, na.rm = TRUE)
var(AC_Avg_MC_Population_ByDonor$AMC_Log_Stem_Biomass, na.rm = TRUE)
```
